# Generated by scripts/homebrew-formula.py from release SHA256SUMS.
class Exr < Formula
  desc "Standalone and SSH client for ExetRouter"
  homepage "https://github.com/mocki-toki/exetrouter"
  version "0.2.1"
  license "MIT"
  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/mocki-toki/exetrouter/releases/download/v0.2.1/exetrouter-aarch64-apple-darwin.tar.gz"
      sha256 "04c0f6438d2924679ab8db52cd7ff48a3a0c982c0bbe73558da8a840b73b7b71"
    end
    on_intel do
      url "https://github.com/mocki-toki/exetrouter/releases/download/v0.2.1/exetrouter-x86_64-apple-darwin.tar.gz"
      sha256 "0cc129f82cd1e3bbad7d3801bc4c73123251943dd1ae22634b698a01d63c2286"
    end
  end

  def install
    bin.install "exr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/exr --version")
  end
end
