# Generated by scripts/homebrew-formula.py from release SHA256SUMS.
class Exr < Formula
  desc "Standalone and SSH client for ExetRouter"
  homepage "https://github.com/mocki-toki/exetrouter"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/mocki-toki/exetrouter/releases/download/v0.2.0/exetrouter-aarch64-apple-darwin.tar.gz"
      sha256 "a462fd7352b4465755c83763a7475abb0cd7e1cce0ce708a7600a733fdb301bf"
    end
    on_intel do
      url "https://github.com/mocki-toki/exetrouter/releases/download/v0.2.0/exetrouter-x86_64-apple-darwin.tar.gz"
      sha256 "61196e0d23c75e1f50d64c7c912b2dfe85d31ba3c316928f8dfbadbde8deba22"
    end
  end

  def install
    bin.install "exr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/exr --version")
  end
end
