#!/usr/bin/env python3
"""Generate the macOS binary-only Homebrew formula from published checksums."""
import re
import sys
from pathlib import Path


def formula(version, sums):
    if not re.fullmatch(r'[0-9]+\.[0-9]+\.[0-9]+', version):
        raise ValueError('invalid version')
    checksums = {}
    for line in sums.splitlines():
        digest, name = line.split()
        if not re.fullmatch(r'[0-9a-f]{64}', digest) or name in checksums:
            raise ValueError('invalid or duplicate checksum')
        checksums[name] = digest
    base = f'https://github.com/mocki-toki/exetrouter/releases/download/v{version}'
    arm = 'exetrouter-aarch64-apple-darwin.tar.gz'
    intel = 'exetrouter-x86_64-apple-darwin.tar.gz'
    return f'''# Generated by scripts/homebrew-formula.py from release SHA256SUMS.
class Exr < Formula
  desc "Standalone and SSH client for ExetRouter"
  homepage "https://github.com/mocki-toki/exetrouter"
  version "{version}"
  license "MIT"
  depends_on :macos

  on_macos do
    on_arm do
      url "{base}/{arm}"
      sha256 "{checksums[arm]}"
    end
    on_intel do
      url "{base}/{intel}"
      sha256 "{checksums[intel]}"
    end
  end

  def install
    bin.install "exr"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/exr --version")
  end
end
'''


if __name__ == '__main__':
    version, checksums, output = sys.argv[1:]
    Path(output).write_text(formula(version.removeprefix('v'), Path(checksums).read_text()))
